apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        #image: 10.98.83.18:5000/demo:0.0.1-taehun
        image: demo:0.0.1-taehun
        imagePullPolicy: Never
        ports:
          - protocol: TCP
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
      #type: NodePort
    #  - port: 25000
    #targetPort: 80
    #protocol: TCP
    #name: http
  selector:
    app: demo
