replicaCount: 1
 
image:
  repository: "docker-registry.jenkins.svc:5000/test/test"
  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 8080
 
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: demo.test.com
      paths:
        - path: /
          pathType: ImplementationSpecific
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
 
livenessProbe:
  httpGet:
  tcpSocket:
    port: 8080
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http